version: '3'

services:
    mongodb:
        container_name: mongodb
        hostname: mongodb
        image: docker.io/bitnami/mongodb:7.0
        environment:
            - MONGODB_PORT_NUMBER=${MONGODB_PORT:-27017}
            - MONGODB_ROOT_USER=${MONGODB_USERNAME}
            - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        ports:
            - '${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}'
        volumes:
            - 'mongodb_data:/bitnami/mongodb'
        networks:
            - the_next_techcell_backend

    redis:
        container_name: redis
        hostname: redis
        image: docker.io/bitnami/redis:7.2
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
            - REDIS_PORT_NUMBER=${REDIS_PORT:-6379}
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
        volumes:
            - 'redis_data:/bitnami/redis/data'
        networks:
            - the_next_techcell_backend
        restart: unless-stopped

    rabbitmq:
        container_name: rabbitmq
        hostname: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.12
        ports:
            - '4369:4369'
            - '5551:5551'
            - '5552:5552'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        environment:
            - RABBITMQ_SECURE_PASSWORD=yes
            - RABBITMQ_LOGS=-
            - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
            - RABBITMQ_NODE_PORT_NUMBER=${RABBITMQ_PORT:-5672}
            - RABBITMQ_MANAGEMENT_PORT_NUMBER=${RABBITMQ_MANAGEMENT_PORT:-15672}
        volumes:
            - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
        networks:
            - the_next_techcell_backend
        restart: unless-stopped

networks:
    the_next_techcell_backend:
        driver: bridge

volumes:
    mongodb_data:
        driver: local
    redis_data:
        driver: local
    rabbitmq_data:
        driver: local
