version: '3'

services:
    api:
        container_name: api
        hostname: api
        build:
            context: .
            dockerfile: .apps/server/Dockerfile
        image: lehuygiang28/the_next_tech_cell:${COMPOSE_TAG:-latest}
        ports:
            - ${API_PORT:-8000}:${API_PORT:-8000}
        env_file:
            - .env
        volumes:
            - the_next_tech_cell_data:/app
        networks:
            - the_next_techcell_backend
        restart: unless-stopped

networks:
    the_next_techcell_backend:
        driver: bridge

volumes:
    the_next_tech_cell_data:
        driver: local
    redis_data:
        driver: local
