/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "mail-context": {
        "CONFIRM_EMAIL": {
            "title": string;
            "text1": string;
            "text2": string;
            "text3": string;
            "btn1": string;
        };
        "RESEND_CONFIRM_EMAIL": {
            "title": string;
            "text1": string;
            "text2": string;
            "text3": string;
            "btn1": string;
        };
        "RESET_PASSWORD": {
            "title": string;
            "text1": string;
            "text2": string;
            "text3": string;
            "text4": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
