export const AuthErrorCodeEnum = {
    EmailAlreadyExists: 'auth.emailAlreadyExists',
    UserNotFound: 'auth.userNotFound',
    EmailAlreadyConfirmed: 'auth.emailAlreadyConfirmed',
    InvalidHash: 'auth.invalidHash',
    WrongProvider: 'auth.wrongProvider',
    WrongEmailOrPassword: 'auth.wrongEmailOrPassword',
    MissingOldPassword: 'auth.missingOldPassword',
    InvalidAddress: 'auth.invalidAddress',
    InvalidImageId: 'auth.invalidImageId',
    AccessTokenInvalid: 'auth.accessTokenInvalid',
    AccessTokenRevoked: 'auth.accessTokenRevoked',
    RefreshTokenInvalid: 'auth.refreshTokenInvalid',
    RefreshTokenRevoked: 'auth.refreshTokenRevoked',
};
